/*
File : makefile
Created : 24-03-27
Authior : °íº´ÇÐ
*/
librarySystem:librarySystem_main.o librarySystem_struct.o librarySystem_function.o
  gcc -o librarySystem librarySystem_main.c librarySystem_struct.c librarySystem_function.c

librarySystem_main.o: librarySystem_main.c
  gcc -c librarySystem_main.c

librarySystem_struct.o: librarySystem_struct.c
  gcc -c librarySystem_struct.c

librarySystem_function.o: librarySystem_function.c
  gcc -c librarySystem_function.c